name: FinXpress
description: Revamping Financial Literacy in India

publish_to: 'none'

version: 1.0.5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: "^4.1.2"
  html_unescape: ^2.0.0
  localstorage: any
  cached_network_image: ^3.0.0
  flutter_svg: any
  http: ^0.13.3
  logger: ^1.0.0
  shared_preferences: ^2.0.5
  provider: ^5.0.0
  cloud_firestore: ^2.0.0
  firebase_core: ^1.2.1
  intl: ^0.17.0
  url_launcher: ^6.0.3
  flutter_html: any
  firebase_auth: ^1.1.0
  google_sign_in: ^5.0.2
  flutter_facebook_login: ^3.0.0
  firebase_messaging: ^10.0.1
  platform_device_id: ^1.0.1
  flutter_local_notifications: ^6.0.0
  firebase_analytics: ^8.0.0
  material_floating_search_bar: ^0.3.4
  share: ^2.0.1
  day_night_switcher: ^0.2.0+1
  firebase_dynamic_links: ^2.0.2
  firebase_storage: ^8.1.0
  fluttertoast: ^8.0.7
  double_back_to_close_app: ^2.0.1
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  colorful_safe_area: ^0.3.0
  html: ^0.15.0
  path_provider: ^2.0.2
  screenshot: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  image_path: "assets/images/logo_transparent.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/facebook.svg
    - assets/icons/google.svg
    - assets/icons/linkedin.svg
    - assets/icons/instagram.svg
    - assets/icons/telegram.svg
    - assets/icons/twitter.svg
    - assets/icons/play_store.svg
    - assets/images/intro1.png
    - assets/images/bookmark.png
    - assets/images/intro2.png
    - assets/images/intro3.png
    - assets/images/logo_transparent.png
    - assets/images/kip.jpg
    - assets/images/sign_in.png
    - assets/icons/drawer.svg
    - assets/icons/timer.svg
    - assets/icons/logo_transparent.svg
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf